name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      - run: export AWS_ACCESS_KEY_ID=ThisIsTheAccessKeyId
      - run: export AWS_SECRET_ACCESS_KEY=ThisIsRequiredButNotUsed
      - run: docker pull amazon/dynamodb-local
      - run: docker run -d -p 8000:8000 amazon/dynamodb-local
      - run: docker ps -a
      - run: echo "$AWS_ACCESS_KEY_ID"