name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - run: export AWS_ACCESS_KEY_ID=ThisIsTheAccessKeyId
      - run: export AWS_SECRET_ACCESS_KEY=ThisIsRequiredButNotUsed

      - name: setup-docker
        run: |
          docker pull amazon/dynamodb-local
          docker run -d -p 8000:8000 amazon/dynamodb-local
          docker ps -a

      - run: echo "$AWS_ACCESS_KEY_ID"

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: semantic-release
        run: |
          npm install -g semantic-release @semantic-release/exec
          semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_GRADLE_PROJECT_ossrhUsername: ${{ secrets.OSSRH_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{ secrets.OSSRH_TOKEN_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY_ASCII }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}